apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app
spec:
  destination:
    name: ''
    namespace: poc-clh-5
    server: 'https://kubernetes.default.svc'
  source:
    path: helm
    repoURL: 'https://github.com/VictorFernandezArias/poc-gitops-github.git'
    targetRevision: main
    helm:
      valueFiles:
        - values-prod.yaml
  sources: 
  - path: helm
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: main
    helm:
      valueFiles:
      - $values/values-prod.yaml
  - ref: values
    repoURL: https://github.com/VictorFernandezArias/poc-gitops-github-values.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
